sudo: required
services:
    - docker

before_install:
    - docker build -t rlag1/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rlag1/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    regin: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-855528127402"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
